Рефакторинг приложения c использованием Dependency Injection
Kimp13/clubhouse pull request #11
Opened 2021-04-22 17:06 UTC by Kimp13

Данная веточка соединила в себе одновременно домашнее задание и курсовую работу.

## DI
Инъекциями стали:
- ContactRepository
- DatabaseModule
  - ContactDatabase
  - ContactLocationDao
 
Все они требуются на протяжении жизни приложения, поэтому помечены как `@Singleton`.

## Местоположение контактов
Контактам теперь можно задать местоположение, воспользовавшись картой Гугл, API-ключ для которой содержится в `local.properties` под кодовым наименованием `MAPS_API_KEY`.

## Обратный геокодинг
Для обратного геокодинга пока используется обычный `Geocoder`. Получать API-ключ Яндекса я на данный момент не стал, потому что при создании аккаунта разработчика необходимо согласиться на вовсе не маленькие условия использования, испугавшие меня.

2021-04-24 17:56 UTC, KalimullinIlnaz commented
Там кнопочку request review ещё нужно нажимать)

2021-04-24 18:10 UTC, Kimp13 commented
> Там кнопочку request review ещё нужно нажимать)

Принял к сведению

2021-04-25 07:08 UTC, murrcha commented
> Использовать я решил рекомендуемый разработчиками Hilt.

В данном задании необходимо использовать Dagger2
 
Что касается курсовой, то лучше ее выносить в отдельный ПР и прикреплять к соответствующему заданию
Иначе сейчас задание по курсовой не сдано

2021-04-25 07:14 UTC, murrcha requested changes
Оставила комментарий

2021-04-25 07:25 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +    lateinit var repository: ContactRepository
репозиторий во фрагменте? его не должно быть здесь

2021-04-25 07:26 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +    lateinit var repository: ContactRepository
Аналогично, репозитория здесь не должно быть

2021-04-25 07:27 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +            viewAdapter = ContactAdapter(repository) {
передавать репозиторий в адаптер - плохая идея
в адаптер нужно передавать только данные

2021-04-25 07:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ContactApplication.kt
> +@HiltAndroidApp
Нужен Dagger 2

2021-04-25 18:54 UTC, Kimp13 commented
> Что касается курсовой, то лучше ее выносить в отдельный ПР и прикреплять к соответствующему заданию
> Иначе сейчас задание по курсовой не сдано

Нужно сделать отдельную ветку с отдельным кодом, или просто сделать ПРы с разным описанием?

2021-04-26 07:56 UTC, Kimp13 commented
Извиняюсь за, возможно, глупый вопрос, но _Re-request review_ тоже надо нажимать?

2021-04-26 08:15 UTC, murrcha commented
> Извиняюсь за, возможно, глупый вопрос, но _Re-request review_ тоже надо нажимать?

Нет, необязательно ) я вижу твои PR и без этого

2021-04-26 08:19 UTC, Kimp13 commented
> > Извиняюсь за, возможно, глупый вопрос, но _Re-request review_ тоже надо нажимать?
> 
> Нет, необязательно ) я вижу твои PR и без этого

Принял к сведению x2

2021-04-26 08:20 UTC, murrcha commented
> Нужно сделать отдельную ветку с отдельным кодом, или просто сделать ПРы с разным описанием?

Лучше разделить по разным веткам: ветка дз отдельно, ветка курсовой отдельно. Так проще смотреть.

2021-04-26 08:21 UTC, Kimp13 commented
> > Нужно сделать отдельную ветку с отдельным кодом, или просто сделать ПРы с разным описанием?
> 
> Лучше разделить по разным веткам: ветка дз отдельно, ветка курсовой отдельно. Так проще смотреть.

Будет исполнено

2021-04-26 08:21 UTC, closed without merging