Рефакторинг приложения с использованием DI
Kimp13/clubhouse pull request #12
Opened 2021-04-26 09:18 UTC by Kimp13

В приложении теперь используется инъекция зависимостей, осуществляемая с помощью Dagger 2.

## Зависимости
- `@Singleton ContactRepository`
- `AppModule`

## Области видимости
- `@ViewModelScope`
- `@ServiceScope`

## Компоненты
- `AppComponent`
  - `ContactViewModelComponent`
  - `StartedContactServiceComponent`

2021-04-26 19:20 UTC, murrcha commented on app/build.gradle
> +    annotationProcessor "com.google.dagger:dagger-compiler:$dagger_version"
annotationProcessor - для чего?

2021-04-26 19:24 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/repositories/ContactRepository.kt
>          context: Context,
context: Context - это можно инжектить в конструктор репозитория и не нужно будет передавать в метод

2021-04-26 19:27 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactDetailsViewModel.kt
> +    lateinit var repository: ContactRepository
репозиторий нужно инжектить в конструктор вьюмодели

2021-04-26 19:28 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactDetailsViewModel.kt
> +    lateinit var repository: ContactRepository
Создавать `ViewModelFactory`?

2021-04-26 19:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactListViewModel.kt
> +    lateinit var repository: ContactRepository
нужен инжект в конструктор вьюмодели

2021-04-26 19:28 UTC, murrcha requested changes
Оставила комментарии

2021-04-27 04:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactDetailsViewModel.kt
> +    lateinit var repository: ContactRepository
да

2021-04-27 09:56 UTC, Kimp13 commented
Пока что осуществляется инъекция в поля фрагментов. У такого подхода есть конкурент в виде инъекции в поля активности и конструкторы фрагментов при помощи `FragmentFactory`. Соперник располагает расширенной областью видимости `ViewModelFactory`, которую, теоретически, можно увеличить и до всего протяжения жизни активности, включая изменения конфигурации.

Стандартный вопрос: _что делать?_

2021-04-27 10:15 UTC, murrcha commented
> Пока что осуществляется инъекция в поля фрагментов. У такого подхода есть конкурент в виде инъекции в поля активности и конструкторы фрагментов при помощи `FragmentFactory`. Соперник располагает расширенной областью видимости `ViewModelFactory`, которую, теоретически, можно увеличить и до всего протяжения жизни активности, включая изменения конфигурации.
> 
> Стандартный вопрос: _что делать?_

во фрагменте можно оставить инжект фабрики в поле

2021-04-27 10:29 UTC, Kimp13 commented
> > Пока что осуществляется инъекция в поля фрагментов. У такого подхода есть конкурент в виде инъекции в поля активности и конструкторы фрагментов при помощи `FragmentFactory`. Соперник располагает расширенной областью видимости `ViewModelFactory`, которую, теоретически, можно увеличить и до всего протяжения жизни активности, включая изменения конфигурации.
> > Стандартный вопрос: _что делать?_
> 
> во фрагменте можно оставить инжект фабрики в поле

Тогда пришло мне время сдаваться

2021-04-27 10:45 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/di/modules/AppModule.kt
> +    fun provideContext(): Context {
Не указан scope

2021-04-27 10:48 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactFragment.kt
> +        (activity?.application as? ContactApplication)?.applicationComponent
до super

2021-04-27 11:52 UTC, murrcha approved these changes

2021-04-27 11:53 UTC, merged