Рефакторинг приложения с использованием Clean Architecture
Kimp13/clubhouse pull request #13
Opened 2021-05-01 13:03 UTC by Kimp13

## Clean Architecture
Приложение подверглось разбиению на модули:
- `entities`
- `interactors`
- `presenters`
- `platform` (платформенный слой)
- `app` (DI)

## DI
Теперь используется `FragmentFactory` и инъекция в конструкторы фрагментов, а `MainActivity` удостоилась инъекции полей. Это сделано, потому что создание фрагментов в модуле `platform`, как мне показалось, невозможно изменить в модуле `app`.

## Timber
`Timber.d` временно заменён на `println` в модуле `presenters`. Является ли Timber одной из тех библиотек, что можно включать не только в модули `platform` и `app`?

2021-05-01 17:42 UTC, murrcha requested changes
По заданию нужно выделить 3 модуля
- domain c entities и interactors
- application - di конфигурация
- presentation - ui часть, вьюмодели, репозитории, детали реализации

то есть из 5ти нужно оставить 3

2021-05-01 17:47 UTC, murrcha commented on interactors/src/main/java/com/example/interactors/ContactInteractor.kt
> +class ContactInteractor(
У тебя один интерактор на все приложение?

2021-05-01 17:50 UTC, murrcha commented on platform/src/main/java/com/example/platform/adapters/items/ContactListItem.kt
> +    data class Entity(val contact: com.example.entities.SimpleContactEntity) :
com.example.entities.SimpleContactEntity - в импорт

2021-05-01 17:50 UTC, murrcha commented on platform/src/main/java/com/example/platform/delegates/ReminderDelegate.kt
> +        contact: com.example.entities.ContactEntity
в импорт

2021-05-01 17:52 UTC, murrcha commented on presenters/src/main/java/com/example/presenters/ContactDetailsViewModel.kt
> +                /*Timber.d*/println("ContactDetailsViewModel job cancelled\n$e")
println - не нужно использовать
оставь Timber

2021-05-04 15:39 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/InteractorModule.kt
> +    ): SimpleContactListInteractor {
Необходимо чтобы был интерфейс и его реализация
Предоставляем реализацию через интерфейс

2021-05-04 15:40 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/InteractorModule.kt
> +        return ContactDetailsInteractor(contactRepository)
Аналогично, разделить на интерфейс и реализацию

2021-05-04 15:40 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/InteractorModule.kt
> +        return ContactListInteractor(contactRepository)
Аналогично

2021-05-04 15:42 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/ViewModelModule.kt
> +class ViewModelModule {
Такой модуль разрастется в итоге
Лучше под экран выделить модуль и предоставлять в нем и вьюмодель и интерактор

2021-05-04 15:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Здесь не должно быть активити

2021-05-04 15:48 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +interface MainActivityComponent {
почему 2 скоупа?

2021-05-04 15:48 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/components/ServiceComponent.kt
> +interface ServiceComponent {
для чего 2 скоупа?

2021-05-04 15:50 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +interface MainActivityComponent {
Потому что `ContactDetailsInteractor` используется и в сервисе, и в активности - я сделал ему свою область видимости, которая затем необходима компонентам, чтобы они смогли использовать такую зависимость.

2021-05-04 15:51 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/services/InjectedBirthdayNotificationService.kt
> +    override lateinit var interactor: ContactDetailsInteractor
если скоуп указывался только для этого интерактора, то лучше для сервиса сделать отдельный интерактор.

2021-05-04 15:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/services/InjectedRebootReminderService.kt
> +    override lateinit var interactor: ContactListInteractor
аналогично, нужно сделать отдельный интерактор для сервиса

2021-05-04 15:53 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Куда и как тогда производить инъекцию?

2021-05-04 15:55 UTC, murrcha requested changes
Оставила замечания

2021-05-04 15:59 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +interface MainActivityComponent {
нужно разделить

2021-05-04 16:02 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
У меня, конечно, появилась идея реализовать приложением интерфейс, описанный в `presentation`, и получать через него фрагменты с инъекцией зависимостей...

2021-05-04 16:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
в модуле presentation у тебя будут интерфейсы контейнеров
в модуле application у тебя будут контейнеры, которые условно "реализуют" эти интерфейсы

например, в presentation у тебя интерфейс
```
interface ContactListContainer {
    fun inject(contactListFragment: ContactListFragment)
}
```
в application у тебя условная "реализация" этого интерфейса
```
@ContactsListScope
@Subcomponent(modules = [ContactListModule::class])
interface ContactListComponent : ContactListContainer
```
инжект как обычно через AppContainer (AppComponent)  в onCreate или onAttach фрагмента

2021-05-04 17:26 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Но ведь нам недоступна аннотация `@Inject` во фрагменте?

2021-05-04 18:37 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
почему?

2021-05-04 18:43 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
А если аннотация доступна и, соответственно, у нас в gradle-зависимостях находится Dagger, зачем разделять два модуля `presentation` и `app`?

2021-05-04 18:46 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Чтобы разделить конфигурацию DI и presentation слой в соответствии с заданием

2021-05-04 18:46 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Но ведь получается, что `presentation` тоже частично берёт на себя конфигурацию DI?

2021-05-04 18:48 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
почему?

2021-05-04 19:07 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
Я переосмыслил ДЗ, жизнь и вселенную. Похоже, я неправильно понимал, что имеется в виду под _конфигурацией DI_.

Получается, что при желаемом положении дел мы в `presentation` лишь указываем, **что** нам нужно получить, а вот **как** мы это получаем (то есть все компоненты и Dagger-модули) - это уже прерогатива gradle-модуля `app`?

2021-05-04 19:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/activities/InjectedMainActivity.kt
> +class InjectedMainActivity : MainActivity() {
да, так

2021-05-04 20:07 UTC, Kimp13 commented
Отдельные интеракторы для сервисов я создавать не стал, поскольку, когда я последовал замечанию и разделил модули на экраны, необходимость двух областей видимости отпала сама собой.

2021-05-05 13:24 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/services/StartedContactService.kt
> +interface ServiceComponent {
Лучше вынести в отдельный package все эти интерфейсы для контейнеров

2021-05-05 13:28 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/services/RebootReminderService.kt
> +    abstract val interactor: ContactListInteractor
сделай для сервисов свой интерактор

2021-05-05 13:30 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/services/BirthdayNotificationService.kt
> +    lateinit var interactor: ContactDetailsInteractor
аналогично, у сервисов пусть будет свой отдельный интерактор, не нужно путать их с интеракторами для фрагментов

2021-05-05 13:33 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/fragments/ContactFragment.kt
>              ?.contactFragmentComponent()
все таки нужно разделить на разные компоненты: для списка один, для деталей - другой.

2021-05-05 13:37 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/scopes/ContactFragmentScope.kt
> +annotation class ContactFragmentScope
Разделить скоупы для экранов: список, детали

2021-05-05 17:08 UTC, Kimp13 commented
Я сделал отдельные **реализации** интеракторов для сервисов и фрагментов, но интерфейсами они пользуются одними и теми же.

### двойные скоупы...
От чего ушёл, к тому и пришёл: двойная область видимости компонентов. На сей раз компонентам фрагментов сильно понадобилась `ViewModelFactory`. Я думаю, что ей стоит жить на протяжении жизни активности, а не фрагмента, поэтому выделенная область видимости обоснована. По крайней мере, до первого опровержения :)

2021-05-05 17:10 UTC, Kimp13 commented
Вопрос по курсовой: удобнее разбить нововведения на кусочки, или предоставить всё сразу (пока что без задания на выбор)?

2021-05-05 18:44 UTC, murrcha commented
> ### двойные скоупы...

можно избежать двойных скоупов
фабрику также предоставлять в модуле экрана
к примеру, сама фабрика для вьюмодели

```
class ViewModelFactory @Inject constructor(
    private val viewModelMap: Map<Class<out ViewModel>, ViewModel>
) : ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        return viewModelMap[modelClass] as T
    }
}
```
и метод предоставляющий эту фабрику в модуле экрана
```
    @Provides
    @ContactDetailsFragmentScope
    fun bindViewModelFactory(
        map: Map<Class<out ViewModel>,
            @JvmSuppressWildcards ViewModel>
    ) : ViewModelProvider.Factory {
        return ViewModelFactory(map)
    }
```

2021-05-05 18:48 UTC, murrcha commented
> Вопрос по курсовой: удобнее разбить нововведения на кусочки, или предоставить всё сразу (пока что без задания на выбор)?

удобнее, конечно, смотреть по фичам
можно к заданию по курсовой крепить ПР с фичей, после проверки мержить и крепить новый
плюс будет понятно что уже готово, а что еще нет

2021-05-05 18:48 UTC, murrcha approved these changes
Все хорошо, разве что можно убрать двойные скоупы

2021-05-05 18:48 UTC, Kimp13 commented
> > Вопрос по курсовой: удобнее разбить нововведения на кусочки, или предоставить всё сразу (пока что без задания на выбор)?
> 
> удобнее, конечно, смотреть по фичам
> можно к заданию по курсовой крепить ПР с фичей, после проверки мержить и крепить новый
> плюс будет понятно что уже готово, а что еще нет

Понял, принял

2021-05-05 18:50 UTC, Kimp13 commented
Забыл цифру 2 как страшный сон

2021-05-05 18:50 UTC, merged

2021-05-05 18:51 UTC, murrcha commented
> Забыл цифру 2 как страшный сон

Она еще может пригодиться ) в будущем