Пользовательский интерфейс указания местоположения
Kimp13/clubhouse pull request #14
Opened 2021-05-05 20:08 UTC by Kimp13

Эээээ... я попытался выделить первый пункт, но всё равно получилась тысяча строк :crying_cat_face:. Возможно, пресловутые перемещения пакетов надо выносить в отдельный коммит?

Данный ПР посвящён пользовательскому интерфейсу указания местоположения.
- Появился новый фрагмент и спаренная с ним `ViewModel`. Пользователи, на своё усмотрение, могут предоставить разрешение `ACCESS_COARSE_LOCATION`, чтобы карта открылась примерно там, где они находятся;
- `ContactEntity` обзавёлся полем `location` с интерфейсом `ContactLocation`;
- `local.properties` пополнился API-ключом `MAPS_API_KEY` из Google Maps Platform, позволяющим пользоваться картой и открывающим доступ к геокодингу, который потребуется нам в будущем.

2021-05-05 20:19 UTC, murrcha commented
Ключ лучше не оставлять в истории публичного репозитория, можно оставить фейк вместо него, переписав текущий коммит, реальный пусть хранится локально.

2021-05-06 07:22 UTC, Kimp13 commented
> Ключ лучше не оставлять в истории публичного репозитория, можно оставить фейк вместо него, переписав текущий коммит, реальный пусть хранится локально.

Создать фейковый `local.properties`? Просто он уже и так в `.gitignore`.

2021-05-06 19:18 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/fragments/ContactLocationFragment.kt
> +        context.getSharedPreferences(
SharedPreferences - это как и бд, источник данных, нужно вынести в репозиторий, скрыть за интерфейсом и предоставлять через di

2021-05-06 19:21 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +                    LocationServices.getFusedLocationProviderClient(
Аналогично, это тоже источник данных, выносим за абстракцию, предоставляем через di

2021-05-06 19:22 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +    suspend fun submit(contactId: Long) {
у вьюмодели не должно быть suspend функций

2021-05-06 19:28 UTC, Kimp13 commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +    suspend fun submit(contactId: Long) {
Обернуть в `LiveData`?

2021-05-06 19:29 UTC, murrcha commented on domain/src/main/java/com/example/domain/entities/ContactLocation.kt
> +interface ContactLocation {
Все таки это сущность, не контракт, нужно описать как data class

2021-05-06 19:31 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/data/entities/ContactLocationEntity.kt
> +) : ContactLocation, Parcelable
В данном случае это сущность для хранения данных, она не обязана реализовывать ContactLocation
То есть domain сущности - это одно, сущности для хранения - это другое
При использовании выполняется маппинг из одной в другую, исходя из потребности

2021-05-06 19:36 UTC, murrcha commented
> * `local.properties` пополнился API-ключом `MAPS_API_KEY` из Google Maps Platform, позволяющим пользоваться картой и открывающим доступ к геокодингу, который потребуется нам в будущем.

тогда не соберется проект без этого файла, сборка потребуется на CI для следующей лекции

2021-05-06 19:39 UTC, murrcha requested changes
Оставила комментарии

2021-05-06 19:40 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +    suspend fun submit(contactId: Long) {
зачем?

2021-05-06 19:44 UTC, Kimp13 commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +    suspend fun submit(contactId: Long) {
Для того, чтобы пока значение записывалось в БД, у пользователя крутился `ProgressBar`.

2021-05-07 07:48 UTC, Kimp13 commented
Запушил фейковый `local.properties`.

2021-05-07 07:55 UTC, Kimp13 commented
Насчёт стейтов: теперь `address = null` вкупе с `progress = true` означает, что поле ещё грузится, потому ответственность формирования строки типа _Местоположение: 1,2345, 6,7890_ было перенесено с фрагмента на вьюмодель.

2021-05-08 18:17 UTC, murrcha commented on domain/src/main/java/com/example/domain/interactors/implementations/MapControlsClarificationInteractorImpl.kt
> +/* Самое сложное - назвать классы... */
если можно обойтись без комментариев - лучше обойтись

2021-05-08 18:18 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/data/repositories/FusedClientLocationRepository.kt
> +            Timber.d("Security exception\n$e")
`Timber.d` -> `Timber.e`

2021-05-08 18:21 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/fragments/ContactLocationFragment.kt
> +    lateinit var interactor: MapControlsClarificationInteractor
никаких интеракторов во фрагменте быть не должно

фрагмент должен обращаеться к вьюмодели, а уже вьюмодель обращается к интерактору

2021-05-08 18:22 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/fragments/ContactLocationFragment.kt
> +        if (!interactor.areMapControlsClarified()) {
убрать интерактор, сделать через вьюмодель

2021-05-08 18:22 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/fragments/ContactLocationFragment.kt
> +            interactor.writeMapControlsClarified()
убрать интерактор

2021-05-08 18:53 UTC, murrcha requested changes

2021-05-08 18:53 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/ContactLocationModule.kt
> +    ): SharedPreferencesRepository {
если это общий репозиторий, то лучше его вынести на уровень приложения как singleton

2021-05-08 18:53 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/ContactLocationModule.kt
> +    ): LastLocationRepository {
Аналогично, данный репозиторий может использоваться другими, лучше вынести на уровень приложения как  singleton

2021-05-08 18:53 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +                            address = application.getString(
application - убрать из вьюмодели
getString - это скорее ответственность фрагмента 
если очень хочется делать это во вьюмодели,
тогда также через интерактор, в интеракторе через репозиторий и т.д.

то есть через di предоставляем репозиторий с ресурсами и используем его сразу в интеракторе

2021-05-08 19:08 UTC, Kimp13 commented
Секундочку, поторопился и сделал не то

2021-05-08 19:11 UTC, Kimp13 commented
Теперь то 👌

2021-05-08 19:16 UTC, murrcha requested changes

2021-05-08 19:16 UTC, murrcha commented on domain/src/main/java/com/example/domain/repositories/SharedPreferencesRepository.kt
> +    fun writeBoolean(key: String, value: Boolean)
чтение и запись в файл - блокирующие операции, нужен suspend

2021-05-08 19:16 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/data/repositories/CommonSharedPreferencesRepository.kt
> +    override fun getBoolean(key: String) =
suspend + Dispatchers.IO

2021-05-08 19:18 UTC, Kimp13 commented on domain/src/main/java/com/example/domain/repositories/SharedPreferencesRepository.kt
> +    fun writeBoolean(key: String, value: Boolean)
Запись происходит через асинхронный `apply()`, значит, можно не помечать `writeBoolean` как `suspend`?

2021-05-08 19:25 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +    private val clarificationInteractor: MapControlsClarificationInteractor
почему нельзя использовать один интерактор?

2021-05-08 19:29 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/viewmodels/ContactLocationViewModel.kt
> +                withContext(Dispatchers.IO) {
переключение контекста лучше сразу сделать на уровне репозитория
если будет использоваться Room, то там достаточно просто указать suspend без переключения контекста
https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5

2021-05-08 19:44 UTC, murrcha commented on domain/src/main/java/com/example/domain/repositories/SharedPreferencesRepository.kt
> +    fun writeBoolean(key: String, value: Boolean)
в случае с apply запись все равно происходит на главном потоке, но не сразу
если операция будет долгая, то это отразится на пользовательском интерфейсе

2021-05-10 11:44 UTC, murrcha approved these changes
Прикрепи, пожалуйста, к заданию по курсовой apk файл собранный из данной ветки

2021-05-10 12:13 UTC, Kimp13 commented
> Прикрепи, пожалуйста, к заданию по курсовой apk файл собранный из данной ветки

Готово

2021-05-10 15:19 UTC, merged