Модульные тесты напоминаний
Kimp13/clubhouse pull request #17
Opened 2021-05-15 12:34 UTC by Kimp13

## Рефакторинг
`ReminderDelegate` перевоплотился в виде `ReminderRepository` и `DateTimeRepository`.

В `SharedPreferencesRepository` переехал функционал `ReminderDelegate`: `(get|write)String`, `remove` и `all`, а реализация репозитория теперь принимает имя нужных SharedPreferences. В связи с этим я переименовал интерфейс, но до интеракторов руки не дошли. Решил оставить эту честь #15.

## Тестирование
Стабаем `DateTimeRepository`, мокаем `ReminderRepository`, засовываем эту гремучую смесь в `ReminderInteractor` и смотрим, чтобы он вызвал методы у `ReminderRepository` с нужными нам аргументами.

2021-05-17 14:05 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/modules/ContactDetailsModule.kt
> +        interactor: ContactDetailsFragmentInteractor
Для чего в названии Fragment?

2021-05-17 14:20 UTC, murrcha requested changes
Судя по заданию у нас должны быть тесты на двух уровнях:

на доменном слое - для интерактора
на слое презентейшн - для вьюмодели

2021-05-17 14:27 UTC, Kimp13 commented
> Судя по заданию у нас должны быть тесты на двух уровнях:
> 
> на доменном слое - для интерактора
> на слое презентейшн - для вьюмодели

А как поступать в доменном слое с репозиторием, который работает с временем (его реализация там недоступна)?
 - Можно проверять лишь факт вызова метода, не проверяя времени;
 - Либо, так как у репозитория нет зависимостей, его можно сделать `object` или `open class` вместо `interface`, но разрешается ли это при следовании Clean Architecture?

2021-05-17 14:35 UTC, murrcha commented
> А как поступать в доменном слое с репозиторием, который работает с временем (его реализация там недоступна)?
> 
> * Можно проверять лишь факт вызова метода, не проверяя времени;
> * Либо, так как у репозитория нет зависимостей, его можно сделать `object` или `open class` вместо `interface`, но разрешается ли это при следовании Clean Architecture?

На лекции рассказывали, что время также можно вынести за абстракцию
При использовании абстракции - нет зависимости на конкретную реализацию, а соответственно можно выполнить любую подмену реализации, в данном случае для тестов

Аналогично и любой object можно вынести за абстракцию, object выполняет роль уже самой реализации этой абстракции

2021-05-20 06:28 UTC, murrcha approved these changes
Принято

2021-05-20 06:29 UTC, merged