Прокладывание маршрута между контактами
Kimp13/clubhouse pull request #23
Opened 2021-05-22 08:36 UTC by Kimp13

Пункт 5, вариант 1 курсовой работы.

## Новые фрагменты
Появилось полтора новых фрагмента: половинка `ContactNavigationListFragment` (он очень сильно похож на `ContactListFragment` и получил тот же базовый класс) и целый `ContactNavigatorFragment`, который, хоть и имеет общий с `ViewContactLocationFragment` ресурс `layout`, отличается внутренней логикой.

Логика такая: сначала пользователь в `ContactDetailsFragment` тыкает на новую кнопку, делая контакта из этого фрагмента отправной точкой, далее попадает в `ContactNavigationListFragment` и выбирает точку назначения. Оба контакта затем отправляются в `ContactNavigatorFragment` и между ними строится маршрут. Если такового нет, пользователь оповещается диалогом и возвращается обратно в `ContactNavigationListFragment`.

## Репозитории
`ContactRepository` изменился и теперь предоставляет возможность выбрать, кроме поиска, огранниченый круг контактов, что используется для отображения только контактов с местоположением в `ContactNavigationListFragment`.

`LocationRepository` при помощи `DirectionsApi` теперь может строить маршруты.

## Коммуникация с фрагментами
detekt снова не хочет, чтобы у меня было много методов, а значит будут gateway-классы, которые отвечают за коммуникацию с фрагментами. Меня немного смущает перспектива иметь кучу `inner class` в активности, поэтому я выделил это изменение в отдельный коммит.

2021-05-31 05:31 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/data/interceptors/DirectionsInterceptor.kt
> +class DirectionsInterceptor : Interceptor {
Для чего нужен это интерсептор?

2021-05-31 05:35 UTC, murrcha requested changes
Добавь, пожалуйста, apk к заданию с текущим результатом

2021-05-31 07:23 UTC, Kimp13 commented
> Добавь, пожалуйста, apk к заданию с текущим результатом

apk добавил, иду разбираться с ktlint

2021-06-15 14:14 UTC, murrcha commented
Посмотрела сборку, прикрепленную к заданию по курсовой
При переходе на карту (Посмотреть местоположение) приложение крэшится, если у контактов не заданы данные
Необходимо исправить такие крайние случаи и перепроверить работоспособность приложения при различных кейсах

2021-06-15 19:16 UTC, Kimp13 commented
Теперь, если ни у одного контакта нет местоположения, и пользователь открывает карту с местоположением контактов, его попросят задать хотя бы одно. То же самое происходит при открытии списка конечных местоположений маршрута, только в таком случае надо задать, соответственно, два местоположения: начало и конец.

2021-06-15 19:35 UTC, Kimp13 commented
Так как в рекомендованной литературе у меня находится "Чистый код" Роберта Мартина, я не мог пройти стороной и не применить правило бойскаута на примере `ViewContactLocationFragment`. Все функции сделать крошечными, конечно, не получилось, однако я попытался выделить одну ответственность - изменение карты - в класс-помощник. Продолжать ли рефакторинг и далее, в пределах всего проекта? Если да, я думаю, стоить выделить изменения в отдельный ПР.

2021-06-16 18:50 UTC, murrcha commented
> Так как в рекомендованной литературе у меня находится "Чистый код" Роберта Мартина, я не мог пройти стороной и не применить правило бойскаута на примере `ViewContactLocationFragment`. Все функции сделать крошечными, конечно, не получилось, однако я попытался выделить одну ответственность - изменение карты - в класс-помощник. Продолжать ли рефакторинг и далее, в пределах всего проекта? Если да, я думаю, стоить выделить изменения в отдельный ПР.

Если считаешь нужным продолжить рефакторинг и в других местах - делай в отдельном ПР

2021-06-16 18:53 UTC, murrcha commented
Я правильно понимаю, что на текущий момент реализована вся функциональность по курсовой или еще что-то осталось?

2021-06-16 19:02 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/data/repositories/ContactProviderRepository.kt
> +                contactsIds
можно все эти параметры указать одной строкой без переноса на новую строку

2021-06-16 19:05 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/activities/MainActivity.kt
> +    inner class FragmentStackGatewayImpl : FragmentStackGateway {
обязательно делать их inner и описывать в классе активности?

2021-06-16 19:06 UTC, murrcha commented on presentation/src/main/java/com/example/presentation/ui/activities/MainActivity.kt
> +    inner class PermissionGatewayImpl : PermissionGateway {
аналогично, лучше вынести класс в отдельный файл

2021-06-16 19:47 UTC, Kimp13 commented
> Я правильно понимаю, что на текущий момент реализована вся функциональность по курсовой или еще что-то осталось?

Реализована необходимая для сдачи функциональность, но не вся возможная (говоря о вариантах 5 задания).

2021-06-21 13:31 UTC, murrcha approved these changes

2021-06-21 14:34 UTC, merged