Bound ContactService
Kimp13/clubhouse pull request #4
Opened 2021-03-10 17:46 UTC by Kimp13

Добавлен привязанный `ContactService` с публичными асинхронными методами для получения списка контактов и отдельного контакта по идентификатору.

Активность имплементит `interface ContactServiceOwner` с возвращающим объект сервиса методом. Фрагменты, вызывая его, получают доступ к объекту, а затем, используя свою `CoroutineScope`, обращаются к асинхронным методам. В конце коцов, фрагмент обновляет свои `TextView` с данными от сервиса.

На данный момент `ContactService` использует поддельные данные из `MockDataSource`.

2021-03-10 18:44 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactEntity.kt
> +    val emails: Array<String>,
Удобнее использовать List<String>, тогда не потребуется переопределять методы equals  и hashCode, так как они итак генерируются для data класса.

2021-03-10 18:51 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/SimpleContactEntity.kt
> +    constructor(detailedContact: ContactEntity) : this(
Удобнее использовать функции расширения для маппинга одного объекта в другой, 
так называемые extension
Например, можно добавить в файл, где описан класс ContactEntity, такую функцию:
```
fun ContactEntity.toSimple() = SimpleContactEntity(
    name = this.name,
    phoneNumber = this.phoneNumbers.first()
)
```

Обрати внимание, у тебя не обрабатывается ситуация, когда список телефонов может быть пустым
Если ты вызовешь first() на пустом списке то будет исключение 
`throw NoSuchElementException("List is empty.")`

2021-03-10 18:59 UTC, murrcha requested changes

2021-03-10 18:59 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +        get() = job + Dispatchers.Default
Сервис сам должен нести ответственность за то на каком потоке ему выполнять свои задачи.

2021-03-10 18:59 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +val contact = ContactEntity(
Можно вынести это в отдельный класс-объект, типа object MockDataSource

2021-03-10 19:02 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +    arrayOf("Телефон 1", "Телефон 2"),
`arrayOf` -> `listOf`

2021-03-11 15:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +        unbindService(connection)
В обратных вызовах принято писать до super

2021-03-11 16:00 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +        get() = job + Dispatchers.Default
Dispatchers.Default - нужен ли здесь? Fragment - это view, работа с view ведется на главном потоке

2021-03-11 17:08 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/MockDataSource.kt
> +class MockDataSource {
Здесь имела в виду сделать через object 
https://www.baeldung.com/kotlin/classes-vs-singleton-objects

`class MockDataSource` -> `object MockDataSource`

2021-03-11 17:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/MockDataSource.kt
> +    suspend fun getContacts(): Array<SimpleContactEntity> {
suspend и delay здесь не нужны, этот метод просто отдает список контактов.
Используй List вместо Array.

2021-03-11 17:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/MockDataSource.kt
> +    suspend fun getContact(id: Int): ContactEntity {
Аналогично, метод должен просто отдавать контакт

2021-03-11 17:11 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/MockDataSource.kt
> +        return arrayOf(SimpleContactEntity("Имя", "89000000000"))
`arrayOf` -> `listOf`

2021-03-11 17:13 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/MockDataSource.kt
> +            "Имя",
Повторяющиеся строки лучше вынести в приватные поля MockDataSource

2021-03-11 18:34 UTC, murrcha requested changes

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +class MainActivity : AppCompatActivity(), ContactCardClickListener, LiveDataContactServiceOwner {
Меняем `LiveDataContactServiceOwner` -> `ContactServiceOwner`
в котором оставляем только метод `fun getService(): ContactService?`

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +        unbindService(connection)
нет проверки на флаг bound и изменения состояния флага на false

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +    override fun serviceObserver(service: ContactService?) {
Делаем без LiveData
В методе onViewCreated - получаем сервис и запрашиваем данные и выводим полученное
То есть будет выглядеть примерно так
```
serviceOwner?.getService()?.let { service ->
            launch {
                val contact = service.getContactAsync(1)
                binding?.contactCard?.run {
                    contactCardName.text = contact.name
                    contactCardPhone.text = contact.phoneNumbers.firstOrNull() ?: getString(
                        R.string.no_phone_number
                    )
                }
            }
        }
```

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +    override fun serviceObserver(service: ContactService?) {
Также - без LiveData

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactServiceFragment.kt
> +    private var serviceOwner: LiveDataContactServiceOwner? = null
нужно сделать это поле доступным для потомка

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactServiceFragment.kt
> +    private lateinit var job: Job
`lateinit` - лишнее, можно сразу `private val job = Job()`

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactServiceFragment.kt
> +        job.cancel()
Отменяем в onDestroy

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/interfaces/LiveDataContactServiceOwner.kt
> +    var service: MutableLiveData<ContactService>
Убираем LiveData, добавляем метод для получения сервиса

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/interfaces/LiveDataContactServiceOwner.kt
> +    var bound: Boolean
Это поле здесь не нужно

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +    private lateinit var job: Job
Здесь по сути нам не нужен CoroutineScope

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +    fun getContactsAsync() = async {
Здесь async не нужен
Лучше сделай функцию suspend и чтобы она запускалась на другом потоке
```
suspend fun getContactsAsync() = withContext(Dispatcher.IO) { 
    delay(1000)
    MockDataSource.getContacts()
}
```

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +    fun getContactAsync(id: Int) = async {
Аналогично

2021-03-11 18:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactEntity.kt
> +    fun toSimple() = SimpleContactEntity(
Это не функция расширения, хотя так тоже можно, но лучше сделать через расширение
https://kotlinlang.org/docs/extensions.html

2021-03-11 18:35 UTC, murrcha requested changes
Описание PR нужно заполнить

2021-03-11 18:37 UTC, Kimp13 commented
А если в момент, когда фрагмент запрашивает сервис, он ещё не запущен?

2021-03-11 19:30 UTC, murrcha commented
> А если в момент, когда фрагмент запрашивает сервис, он ещё не запущен?

А надо ли нам создавать фрагмент раньше этого момента?
Нам же нужно отобразить данные, то есть можно добавлять фрагмент не в момент создания активности, а в момент получения сервиса в активности (с учетом что у нас активность создается первый раз)

2021-03-11 19:33 UTC, Kimp13 commented
Незаметно ли будет это ожидание для пользователя?

2021-03-11 19:40 UTC, murrcha commented
> Незаметно ли будет это ожидание для пользователя?

В момент загрузки пользователю можно что-то показывать, например, прогрессбар для индикации загрузки, но это уже детали. Даже если добавить фрагмент сразу, то данных еще не будет.

2021-03-12 06:01 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                        launch(Dispatchers.Main) {
для переключения контекста обычно используют `withContext(Dispatchers.Any) {}`
в данном случае переключение не нужно, первый launch уже на Main

2021-03-12 06:03 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +                        launch(Dispatchers.Main) {
Аналогично, первый launch уже на Main

2021-03-12 10:05 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +    private lateinit var contactService: ContactService
Лучше сделать эту переменную nullable
Либо при обращении к ней добавить проверку, инициализирована она или нет
Сейчас такой проверки нет, поэтому возможны крэши

2021-03-12 12:51 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +    private lateinit var contactService: ContactService
Теперь приложение не крэшится, но при повороте экрана сервис не успевает запуститься. Можно записывать данные в `savedInstanceState` - но если переворот экрана произошёл перед тем, как фрагмент получил данные от сервиса, `savedInstanceState` всё равно не будет хранить данных. Использовать ли, в таком случае, `Observable` у `MainActivity` для уведомления фрагментов, или просто пересоздавать фрагмент, когда сервис запускается?

2021-03-12 15:01 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +    private lateinit var contactService: ContactService
В целом идея такая: фрагмент обновляет данные при подключении к сервису. Реализовать можно по-разному. Можно использовать простой коллбек. Фрагмент его реализует и через метод этого коллбека он узнает что сервис подключен и только в этом момент запросит данные и обновит ui. Причем тогда не нужно будет добавлять фрагмент при коннекте. Можно добавлять как обычно. Фрагмент все равно будет уведомлен и сделает то, что ему нужно.

2021-03-14 06:03 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +            onServiceBoundHandler?.invoke(contactService)
По идее, передавать contactService здесь не нужно, его можно получить из getService после того как выполнилось подключение

2021-03-14 06:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +        val service = serviceOwner?.getService()
Здесь нужно упростить для читаемости, сейчас 2 метода с одинаковым названием, лучше разделить
К примеру 
есть метод updateContact(contact: Contact) - обновление данных контакта на ui
есть метод updateUI()  - получение сервиса, получение контакта и вызов updateContact(contact)

2021-03-14 06:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
В onAttach передаем действие, которое нужно выполнить
```
serviceOwner?.setAction {
            updateUI()
        }
```
В onDetach обнуляем
`serviceOwner?.setAction(null)`

2021-03-14 06:53 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +        savedInstanceState?.getParcelable<ContactEntity>(ENTITY_KEY)?.let {
Если есть сохраненное - берем оттуда
Если нет - запрашиваем
```
savedInstanceState?.getParcelable<ContactEntity>(ENTITY_KEY)?.let {
            updateContact(it)
} ?: updateUI()
```

2021-03-14 06:58 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +        if (contactService != null) {
if (bound) - нужно проверять, если подключение

2021-03-14 08:37 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Когда экран поворачивается, у всех фрагментов в бэкстеке проходят коллбэки вплоть до `onCreate` включительно, и лишь у активного все остальные. Причём, похоже, что коллбэки видимого фрагмента исполняются первыми. То есть, `onAttach` у `ContactListFragment` выполняется позже, чем у `ContactDetailsFragment`, а значит у `ContactServiceOwner` сохраняется нежелаемый коллбэк - данные в `ContactDetailsFragment` не обновляются.

Стоит ли вынести работу с коллбэком в `onCreateView`+`onDestroyView`?

2021-03-14 14:33 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Можно сделать так, что каждый фрагмент реализует свою логику по обновлению в соответствии с определенным интерфейсом.
Активность в свою очередь после успешного подключения будет брать активный фрагмент, и если он реализует необходимый интерфейс, вызывать метод этого интерфейса.

2021-03-14 15:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Мне не удалось воспроизвести ситуацию, что ты описал, данные на детальном экране успешно обновляются при пересоздании активности на этом экране. Покажи в коде, как ты это делаешь.

2021-03-14 15:19 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
### Код из суперкласса `ContactServiceFragment`

![image](https://user-images.githubusercontent.com/56446247/111073859-e6de8d00-84f9-11eb-9479-6253918d915c.png)

2021-03-15 06:06 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Лучше кодом в этот PR

2021-03-15 06:17 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +private const val LIST_FRAGMENT_TAG = "fragment_contact_list"
Данные теги принадлежат конкретным фрагментам, константы лучше вынести туда, кому они принадлежат

2021-03-15 06:23 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
В текущем варианте у тебя корректно отрабатывается пересоздание активности на списке и на деталях.

2021-03-15 06:29 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Я переделал с коллбэками у фрагментов, и всё работает, так что конкретно по ситуации нет.
<pre>
Но насчёт кода на будущее:
его выносить вот так?
</pre>

2021-03-15 07:07 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            serviceOwner?.setOnServiceBoundListener {
Нет, это необязательно

2021-03-15 18:54 UTC, murrcha approved these changes
Принято

На будущее: обычно публичные константы идут первыми, после них приватные

2021-03-15 19:00 UTC, merged