Оповещение о дне рождения
Kimp13/clubhouse pull request #5
Opened 2021-03-17 20:20 UTC by Kimp13

Добавлен `ContactBirthdayReceiver`, получающий оповещения от `AlarmManager` о дне рождении контакта. В связи с этим также создан `data class BirthDate`, содержащий число и месяц появления контакта на свет.

Активность создаёт пока что единственный канал оповещений, на который приходят все уведомления о днях рождения. Когда пользователь нажимает на уведомление, `MainActivity` получает `Intent`, содержащий `id` контакта, указанного в оповещении, а затем создаёт `ContactDetailsFragment`, передавая соответствующий `id`. В этом же фрагменте пользователь может подписаться на рассылку или отписаться от неё. Проверка уже существующей подписи осуществляется с помощью `PendingIntent.FLAG_NO_CREATE`.

2021-03-17 20:21 UTC, Kimp13 commented
К сожалению, в `Intent` от `AlarmManager` к `ContactBirthdayReceiver` обнаружились проблемы с передачей `Parcelable` в `extras`, конкретно на моём девайсе решить которые получилось способом, описанным [тут (первый ответ)](https://stackoverflow.com/questions/40480355/pass-serializable-object-to-pending-intent/40515978#40515978), кратко говоря, засунув `Parcelable` в `Bundle` и положив в `extras` сам `Bundle`.

2021-03-17 20:31 UTC, Kimp13 commented
Предыдущее сообщение официально объявляется некорректным и остаётся лишь во благо истории. Читать мне задания надо лучше, пожалуй…

2021-03-18 17:20 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Метод onCreate разрастается, лучше вынести создание канала в отдельный метод

2021-03-18 17:25 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +    private fun setRemainder(button: Button?) {
Предлагаю эту логику вынести, например, в класс ReminderDelegate (он же и будет работать с AlarmManager), иначе лишняя ответственность у фрагмента.

2021-03-18 17:25 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +    private fun cancelRemainder(button: Button?) {
Аналогично, вынести в делегат

2021-03-18 17:31 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                    contactDetailsRemindButton.setOnClickListener {
contactDetailsRemindButton вложена в contactDetailsRemindButton, выглядит запутано, чтобы лучше читалось - упрости

2021-03-18 17:32 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            val intent = Intent(context, ContactBirthdayReceiver::class.java).apply {
Здесь слишком много всего, лучше вынести создание интента в отдельный метод.
Например, createAlarmIntent

2021-03-18 17:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                    contactDetailsRemindButton.setOnClickListener {
можно вместо кнопки использовать переключатель

2021-03-18 17:44 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +    private fun cancelRemainder(button: Button?) {
Пусть делегат несет ответственность за создание интента, проверку есть ли расписание, за создание расписания, за отмену расписания

2021-03-18 17:46 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                    alarmIntent = PendingIntent.getBroadcast(
этого здесь не должно быть, здесь просто текст ставится на кнопку

2021-03-18 17:55 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/receivers/ContactBirthdayReceiver.kt
> +                NotificationManagerCompat.from(context).notify(
Показать уведомление - это логика для отдельного метода

2021-03-18 17:57 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/receivers/ContactBirthdayReceiver.kt
> +                NotificationManagerCompat.from(context).notify(
Не нашла логики по обновлению расписания, чтобы уведомление также показалось и на следующий год

Плюс приложение при запуске сразу отображается на детальном экране, хотя должен быть список

2021-03-18 18:11 UTC, murrcha requested changes
Проверь навигацию, проверь повтор расписания, проверь отмену расписания, сделай рефакторинг 

Если с этим разберешься и будет скучно, то можно проверить будет ли работать расписание после перезагрузки девайса.

2021-03-19 04:07 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/receivers/ContactBirthdayReceiver.kt
> +                NotificationManagerCompat.from(context).notify(
Чтобы обновить расписание, нужно получить дату рождения контакта, и тут мне нужно помочь сделать выбор:
- Передавать дату в `extras` либо как `BirthDate : Parcelable`, либо как два `Int` (по причине, описанной в зачеркнутом комментарии выше)
- Брать сегодняшнюю дату из `Calendar`
- Передавать в `extras` лишь `id` контакта, а в `BroadcastReceiver` стартовать новый сервис, который бы получал все данные контакта и уже распоряжался ими.

2021-03-19 08:24 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/receivers/ContactBirthdayReceiver.kt
> +                NotificationManagerCompat.from(context).notify(
Можно продлить в момент самого события, используя эту же дату

2021-03-19 11:27 UTC, Kimp13 commented
Это пока без перезагрузки

2021-03-19 11:51 UTC, murrcha commented
> Насчёт неё: как я понял, все `PendingIntent`ы сбрасываются, а потому необходимо где-то хранить, например, `id` контактов с подпиской. Стоит ли это делать в `SharedPreferences`?

да, нужно хранить ид контактов, у которых включено напоминание, чтобы потом при получении события, что устройство загружено, можно было восстановить все расписания.
для хранения можно использовать как SP, так и просто запись идентификаторов в файл, при этом важно помнить, что нужно и удалять запись, если пользователь отключил напоминание.

2021-03-19 12:05 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/receivers/ContactBirthdayReceiver.kt
> +                val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
Хорошо бы и здесь использовать делегат, можно сделать существующий делегат object чтобы был один объект на всех

2021-03-19 12:21 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactReminderDelegate.kt
> +class ContactReminderDelegate() {
Под делегатом имела в виду не Delegated properties, а сущность, которая работает с AlarmManager, добавляет расписание, удаляет расписание, проверяет есть ли расписание. Можно обращаться к этой сущности и дергать ее методы, чтобы добавить или удалить расписание или проверить есть ли уже расписание.

2021-03-19 12:22 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactReminderDelegate.kt
> +                Calendar.getInstance().run {
Получение времени тоже в отдельный метод можно вынести

2021-03-19 12:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactReminderDelegate.kt
> +            alarmIntent?.cancel()
для чего второй cancel?

2021-03-19 12:39 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactReminderDelegate.kt
> +            alarmIntent?.cancel()
Вычитал [тут](https://stackoverflow.com/questions/4556670/how-to-check-if-alarmmanager-already-has-an-alarm-set#:~:text=Note%20that%20you%27ll%20need%20to%20call%20both%20alarmManager.cancel(pendingIntent)%20and%20pendingIntent.cancel()%20in%20order%20for%20this%20solution%20to%20return%20false.). Кратко говоря, самый популярный комментарий самого популярного ответа утверждает: чтобы `PendingIntent.FLAG_NO_CREATE` возвращал `null`, необходимо отменять и сам `PendingIntent`.

2021-03-19 14:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactReminderDelegate.kt
> +            alarmIntent?.cancel()
То есть из расписания задача удаляется, а сам интент остается, понятно

2021-03-19 16:57 UTC, Kimp13 commented
Я хотел бы рассмотреть кандидатуру сервиса, запускаемого `BroadcastReceiver`ом при получении сообщения от `AlarmManager`. 
- Сервис упростит локализацию: он будет брать строковые ресурсы для заголовка и текста каждый раз во время получения уведомления, а не один раз при подписке на дни рождения контакта;
- В `Intent` для `BroadcastReceiver` появится возможность передавать лишь `id` контакта, и, следовательно, в `SharedPreferences` для перезагрузки потребуется хранить лишь `id` контактов, на которые пользователь подписан (на данный момент, в моём представлении, потребуется хранить `id` контакта, заголовок и текст уведомления).

Стоит ли следовать такой логике и использовать сервис?

2021-03-19 17:52 UTC, murrcha commented
> Я хотел бы рассмотреть кандидатуру сервиса, запускаемого `BroadcastReceiver`ом при получении сообщения от `AlarmManager`. `BroadcastReceiver` передаёт сервису `id` контакта, затем сервис асинхронно получает данные, отображает уведомление и завершает свою работу.
> 
> * Сервис упростит локализацию: он будет брать строковые ресурсы для заголовка и текста каждый раз во время получения уведомления, а не один раз при подписке на дни рождения контакта;
> * В `Intent` для `BroadcastReceiver` появится возможность передавать лишь `id` контакта, и, следовательно, в `SharedPreferences` для перезагрузки потребуется хранить лишь `id` контактов, на которые пользователь подписан (на данный момент, в моём представлении, потребуется хранить `id` контакта, заголовок и текст уведомления).
> 
> Стоит ли следовать такой логике и использовать сервис?

Учитывая, что не рекомендуется в методе onReceive выполнять какую-то длительную работу, делегировать эту работу кому-то еще вполне можно, стартовать сервис, который выполнит свою работу и завершится, хороший вариант

На счет строковых ресурсов, они доступны и в BroadcastReceiver и в Service

2021-03-20 17:46 UTC, Kimp13 commented
Сервис, который, правда, пришлось сделать `Foreground`, поскольку андроид ругается на запуск заднепланового сервиса при неработающем приложении, готов. Однако, мне тут на пути повстречалась манна небесная в виде `WorkManager`, который, как оказывается, и корутины через `CoroutineWorker` поддерживает, и после перезагрузок девайса ничего восстанавливать не надо. Может, очередной раз рефакторнуть приложение, но уже с `WorkManager`ом?

2021-03-20 18:37 UTC, murrcha commented
> Сервис, который, правда, пришлось сделать `Foreground`, поскольку андроид ругается на запуск заднепланового сервиса при неработающем приложении, готов. Однако, мне тут на пути повстречалась манна небесная в виде `WorkManager`, который, как оказывается, и корутины через `CoroutineWorker` поддерживает, и после перезагрузок девайса ничего восстанавливать не надо. Может, очередной раз рефакторнуть приложение, но уже с `WorkManager`ом?

Да, можно использовать WorkManager, это более актуально сейчас, к тому же в андроид 12 с сервисам ещё жёстче стало. Ещё есть какой-то новый вид jobы для WorkManager, которая должна выполняться незамедлительно.

2021-03-20 20:32 UTC, Kimp13 commented
К сожалению, некоторые вендорные ОС насильно останавливают приложение при свайпе из списка задач, а вместе с ним и `WorkManager`, [как указано здесь](https://stackoverflow.com/questions/50682061/android-is-workmanager-running-when-app-is-closed). Все отложенные работы восстанавливаются только при запуске приложения заново. Так, в том числе, поступает мой Xiaomi. На Pixel-эмуляторе всё работает прекрасно.

Foreground сервис, по-видимому, более надёжен независимо от производителя, и придётся оставить версию с ним.

2021-03-21 14:11 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/BirthdayNotificationService.kt
> +
Желательно ошибку выводить в лог, можно подключить Timber для логирования

2021-03-21 14:12 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/BirthdayNotificationService.kt
> +import com.example.clubhouse.ui.fragments.CONTACT_ARG_ID
Неиспользуемый импорт. При коммите можно включить флаг optimize imports, и такие импорты будут автоматически очищаться.

2021-03-21 14:30 UTC, murrcha requested changes
Отлично! 
Есть пара минорных замечаний

2021-03-21 17:03 UTC, murrcha approved these changes
Отлично, принято
Нужно еще сдать задание в classroom

2021-03-21 17:06 UTC, merged