Получение контактов из Contact Provider
Kimp13/clubhouse pull request #6
Opened 2021-03-24 16:49 UTC by Kimp13

Реализовано получение списка контактов из Contact Provider. В `MockDataSource` методы стали вовсе не mock, а потому произошло великое переименование в `DataSource`. Логика находится именно там, а не в `ContactService`, поскольку получение контактов используется всеми тремя сервисами.

Во многих местах (кроме тех, что в следующем абзаце) `id` пользователя был заменён на `lookup`, он же `LOOKUP_KEY`. Сделано это на основании скромной подписи разработчиков
![image](https://user-images.githubusercontent.com/56446247/112348382-36cf0800-8ce1-11eb-8c7e-ba28fdd193ce.png)
и того, что `LOOKUP_KEY` - ключ, присутствующий в обеих таблицах `ContactsContract.Contacts` и `ContactsContract.Data`.

`_ID` продолжает использоваться как идентификатор уведомлений о днях рождения и идентификатор `PendingIntent`ов. Однако, в базе данных Contact Provider'а `_ID: Long`, а идентификаторы уведомлений и интентов - `Int`, поэтому учитывается только половина `_ID`.

2021-03-25 14:39 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
можно убрать это условие, если это ниже 6ки, то разрешение уже есть по умолчанию

2021-03-25 18:04 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            println()
лишняя инструкция

2021-03-25 18:07 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +            contentResolver.query(
А здесь почему не через DataSource?

2021-03-25 18:16 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +            contentResolver.query(
Потому что другим сервисам такие данные не нужны

2021-03-25 18:29 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +            contentResolver.query(
Тем не менее лучше чтобы все брали из одного места

2021-03-25 18:32 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +                RequestReadContactsPermissionFragment(),
Не вижу этого файла в изменениях

2021-03-25 18:35 UTC, murrcha requested changes
Проверь, все ли файлы сейчас в PR, похоже не хватает некоторых

2021-03-26 06:24 UTC, murrcha requested changes
Проект не собирается с этой ветки.
В PR не хватает следующих используемых сущностей:

ReadContactsRequestDenialListener,
PoppableBackStackOwner,
ReadContactsPermissionRequester,
RequestPermissionDialogDismissListener,
RequestPermissionDialogFragment,
RequestReadContactsPermissionFragment

2021-03-26 17:31 UTC, Kimp13 commented
Исправлена ошибка с неполучением `ContactListFragment`ом `ContactService`а  после перехода по уведомлению.

В `ReminderDelegate.scheduleAlarm()` теперь используются корректные методы `isLeap()`, а также заново записывается 29 февраля на уже високосный год, поскольку, думаю, вышестоящая установка 29 февраля на невисокосный год сбивает с толку `Calendar`.

2021-03-28 10:02 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +                RequestReadContactsPermissionFragment(),
Этот фрагмент избыточен, как и алерт-диалог перед системным диалогом запроса разрешения.
Необходимо сразу запрашивать разрешение, если этого разрешения нет, то есть будет показан сразу системный диалог. Если пользователь не дал разрешение, когда мы запросили, то после этого необходимо показать диалог и написать в нем для чего нам необходимо это:
https://developer.android.com/training/permissions/requesting#explain

2021-03-28 10:08 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/RebootReminderService.kt
> +                        DataSource.getContacts(
Нет проверки, есть ли разрешение на получение контактов.
Пользователь может отозвать разрешение в любое время.

2021-03-28 10:09 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/BirthdayNotificationService.kt
> +                    val contact = DataSource.getContact(
Нет проверки, есть ли разрешение на получение контактов.
Пользователь может отозвать разрешение в любое время.

2021-03-28 10:13 UTC, murrcha requested changes
Оставила комментарии

Плюс крэш

```
java.lang.NullPointerException: it.getString(
              …                        ) must not be null
        at com.example.clubhouse.data.DataSource$getContact$2$2.invokeSuspend(DataSource.kt:146)
```

2021-03-28 10:34 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +                RequestReadContactsPermissionFragment(),
Хорошо, если пользователь во второй раз предоставит разрешение. Но если нет, и при этом нажмёт "не спрашивать снова" или уровень API >= 30?

2021-03-28 15:00 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
> +                RequestReadContactsPermissionFragment(),
Если пользователь нажал "Не спрашивать снова", то мы не можем ничего получить без разрешения.
Вместо контента можно показывать заглушку с надписью почему пусто и кнопкой по которой можно все исправить (для навигации в настройки для включения разрешения).

2021-03-29 06:45 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                        ContentUris.withAppendedId(
Почему не получаем сразу uri в DataSource?

2021-03-29 06:49 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/RequestReadContactsPermissionFragment.kt
> +                        startActivity(
лучше вынести в отдельный метод, чтобы не разрастался onViewCreated

2021-03-29 06:54 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                        ContentUris.withAppendedId(
Меньше памяти тратится на хранение `Long` :)

2021-03-29 06:54 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/ContactService.kt
> +import com.example.clubhouse.data.*
Желательно отключить схлапывание импортов в настройках студии, импорты должны отображаться явно

2021-03-29 07:00 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +                        ContentUris.withAppendedId(
Получается фрагмент у нас вместо того чтобы использовать готовое, делает еще что-то постороннее.
Может тогда вынести в отдельный метод DataSource эти действия по добыче uri?

2021-03-29 07:03 UTC, murrcha approved these changes
Авансом принято
Нужно только исправить минорные замечания

2021-03-29 16:43 UTC, merged