Рефакторинг приложения с использованием паттерна MVVM
Kimp13/clubhouse pull request #7
Opened 2021-04-01 17:07 UTC by Kimp13

`DataSource` был величественно переименован в `Repository`.

В базовом классе `ContactFragment` в связи с рефакторингом вызов `updateUI` был перенесён из `onViewCreated` в `onStart`: в случае, когда фрагмент пересоздаётся и данные во `ViewModel` уже присутствуют, `updateUI` может сработать быстрее, чем `ViewBinding`, происходящий в `onViewCreated`.

2021-04-03 15:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/Repository.kt
> +object Repository {
Repository - так можно назвать, но когда в проекте будет один единственный репозиторий всегда, лучше конкретизировать, какой это репозиторий и для чего, чтобы по названию было понятно

2021-04-03 15:38 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/activities/MainActivity.kt
>  class MainActivity :
В конце класса 2 лишних пустых строки

2021-04-03 15:56 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            viewModel.contact?.value?.let {
Выглядит слишком запутанно, нужно переписать на более читаемый код

Достаточно подписаться в onVIewCreated на поле из вьюмодели и обновлять там ui
Здесь же можно запросить данные по ид у той же вью модели, предварительно проверив разрешение
Когда данные будут получены, в подписку придет контакт и ui обновится

Также лучше убрать родительский класс ContactFragment

2021-04-03 16:13 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +            viewModel.contactList.value?.let {
Аналогично, нужно упростить

2021-04-03 16:51 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactDetailsViewModel.kt
> +                    emit(Repository.getContact(it, lookup))
Здесь лучше просто передавать контекст в репозиторий, а сам репозиторий будет брать из контекста contentResolver

2021-04-03 16:51 UTC, murrcha requested changes
Есть замечания

2021-04-05 15:46 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        lookups: ArrayList<String?>
ArrayList  -> List

2021-04-05 15:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            viewModel.contact?.value?.let {
Не исправлено. Нужно сделать отдельно подписку на лайвдату у вьюмодели, и отдельно запросить данные (предварительно проверив разрешение)

2021-04-05 15:52 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +            viewModel.contactList.value?.let {
Не исправлено. Нужно сделать отдельно подписку на лайвдату у вьюмодели, и отдельно запросить данные (предварительно проверив разрешение)

2021-04-05 15:56 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
>      ContactEntityOwner {
ContactEntityOwner - для чего этот интерфейс?

2021-04-05 17:13 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            viewModel.contact?.value?.let {
А нужно ли проверять, были ли получены уже данные моделью?

Если да, что делать в таком случае?
- Оставлять старые данные
- Сначала передавать старые, затем получать и передавать новые

2021-04-08 13:07 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactDetailsFragment.kt
> +            viewModel.contact?.value?.let {
Сейчас по коду всегда запрашивается у провайдера после создания вью. 
Если этого достаточно, можно оставить. 
Можно добавить swipe to refresh на экран, если хочется обновить данные вручную, например.
Либо по любой другой логике. 
Получается мы один раз подписываемся. А запрашивать можно много раз.
Результат придет в подписку.
Просто обновляем UI тем что приходит.
То есть 1 раз запросил - 1 раз придет.

2021-04-08 13:07 UTC, murrcha approved these changes
Принято

2021-04-08 13:53 UTC, merged