Рефакторинг приложения с использованием RecyclerView
Kimp13/clubhouse pull request #8
Opened 2021-04-08 16:17 UTC by Kimp13

### RecyclerView
В `ContactListFragment` теперь используется `RecyclerView`. `Adapter` для него создан с помощью [AdapterDelegates](https://github.com/sockeqwe/AdapterDelegates).

Реализована `ContactItemDecoration`, создающая разделители в начале списка, в конце списка и между элементами списка.

### Поиск
В `ContactListFragment.onCreateOptionsMenu` в меню инфлейтится `SearchView`.

`ContactListViewModel` запоминает `searchQuery` и применяет поиск заново при переходе по фрагментам или повороте экрана.

### Git
Часть `diff`ов тянется ещё с прошлой ветки, потому что эту я начал раньше, чем смержил предыдущую. И хотя такой ситуации очень нежелательно повторяться снова, я хотел бы узнать, можно ли вообще подобные стечения обстоятельств разрешать, как будто бы всё шло по плану, чего мне не удалось добиться неопытной работой с `cherry-pick`.

2021-04-09 07:03 UTC, murrcha commented
> ### Git
> Часть `diff`ов тянется ещё с прошлой ветки, потому что эту я начал раньше, чем смержил предыдущую. И хотя такой ситуации очень нежелательно повторяться снова, я хотел бы узнать, можно ли вообще подобные стечения обстоятельств разрешать, как будто бы всё шло по плану, чего мне не удалось добиться неопытной работой с `cherry-pick`.

Необходимо сделать сделующее:
Обновить основную локальную метку master или main (то есть подтянуть изменения из remote master)
Текущую ветку с ДЗ нужно обновить в соответствии с master
Для этого нужно сделать rebase текущей ветки на master
Как это сделать проще в студии: 
- переключиться на ветку дз
- выбрать в списке веток ветку master
- в контекстном меню выбрать rebase current onto selected

В таком случае текущие изменения запишутся новым коммитом от последнего коммита в master
При rebase возможны также конфликты, в данном случае лучше выбрать - решить вручную
И уже наглядно посмотреть и решить какие изменения в итоге оставить из двух версий

2021-04-09 08:15 UTC, Kimp13 commented
Магия 😮

2021-04-09 09:28 UTC, murrcha approved these changes
Оставила комментарии

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +                        verticalOffset = resources.getDimensionPixelSize(
Лучше все это задавать через конструктор `ContactListDecoration(parameter)`, можно даже специальную обертку сделать с параметрами, чтобы в конструктор передавать только 1 параметр

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +    var verticalOffset: Int = 0
Перенести эти параметры в конструктор

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +        c: Canvas,
c -> canvas

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +                val x1 = it.left.toFloat()
x1 - лучше сделать говорящие переменные

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +        delegatesManager.addDelegate(
Раз уж используешь AdapterDelegate, давай добавим еще 2 вида ячеек
К примеру, будет ячейка хедера - ячейка в начале списка
В нее добавим статичную надпись с любым текстом, можно с картинкой
И ячейка футера в конце списка
В ней будем выводить сколько всего контактов в списке, например, Всего контактов: [значение]

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +            }, Paint().apply {
Здесь создается много раз Paint, лучше вынести это в переменную и создавать 1 раз при создании декоратора и далее использовать уже ее.

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactAdapterDelegate.kt
> +fun contactAdapterDelegate(clickListener: ContactCardClickListener?) =
`ContactCardClickListener` - можно вместо интерфейсов использовать лямбды

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactAdapterDelegate.kt
> +            findViewById<ImageView>(R.id.contactCardPhoto).run {
в каждом методе `bind` ты вызываешь `findViewById`
это накладно, нужно вынести 
делай это 1 раз при создании

2021-04-09 09:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/delegates/ContactAdapterDelegate.kt
> +                clickListener?.onCardClick(it)
Здесь необходимо передавать позицию, соответственно должна быть проверка на NO_POSITION
А уже в адаптере получать по позиции элемент списка и передавать его дальше

2021-04-09 09:29 UTC, murrcha requested changes
Оставила комментарии

2021-04-11 05:55 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
Предложение добавить 2 доп. вида ячеек было только, если ты используешь AdapterDelegate
Если ты не используешь AdapterDelegate - не нужно делать несколько видов ячеек. 
Для реализации списка с одним типом ячеек можно использовать ListAdapter (с уже реализованным Diff), либо использовать голый RecyclerView, при этом самому реализовав работу с Diff  (можно использовать AsyncListDiffer, либо вручную делать вычисления на отдельном потоке)

2021-04-11 05:57 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +            Вот эта строчка (4 строчки) меня смущает. Что делать?
Нужно определиться, если несколько видов ячеек - использовать  AdapterDelegate.
Если один вид ячеек -  использовать ListAdapter или RecyclerView.

2021-04-11 05:58 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +data class ContactListDecorationProperties(
```
data class ContactListDecorationProperties(
    @Px val verticalOffset: Int = 0,
    @Px val horizontalOffset: Int = 0,
    @Px val junctionWidth: Float = 0F,
    @ColorInt val junctionColor: Int = Color.TRANSPARENT
)
```
Отформатировать

2021-04-11 06:06 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +    private val differ = AsyncListDiffer(
Для чего это здесь? У AdapterDelegate уже все это реализовано, нужно только правильно написать DiffCallback.
Тебе для разных видов ячеек нужно сделать разные делегаты и разные вьюхолдеры. 
Тебе нужно задать разные типы ячеек, это можно сделать через sealed класс

sealed Item {
   object HeaderItem : Item()
   data class ContactItem(val contact: Contact) : Item()
   object FooterItem : Item()
}

Данные типы нужно сравнивать в DiffCallback

Если с этим сложности пока, то оставь один тип ячеек

2021-04-11 06:08 UTC, Kimp13 commented
Просто я не очень понял, как эти ячейки связаны с основными данными, поэтому, по моему разумению, пришлось бы создать `AsyncListDifferDelegationAdapter` от `<Any>`. В данной реализации я использую `AsyncListDiffer` и `AdapterDelegatesManager` только для работы с основным каскадом данных, шапки и подвалы реализуются через обычные `ViewHolder`.

2021-04-11 06:11 UTC, murrcha requested changes
Предлагаю оставить 1 тип ячейки и не использовать AdapterDelegate. 
Вижу пока возникли сложности с пониманием, как это должно работать.
Попробуй разобраться, не получится, оставь 1 тип.
Потом покажу пример, как это можно было сделать.

2021-04-11 06:12 UTC, murrcha commented
> Просто я не очень понял, как эти ячейки связаны с основными данными, поэтому, по моему разумению, пришлось бы создать `AsyncListDifferDelegationAdapter` от `<Any>`. В данной реализации я использую `AsyncListDiffer` и `AdapterDelegatesManager` только для работы с основным каскадом данных, шапки и подвалы реализуются через обычные `ViewHolder`.

Написала выше, как это связано
Есть общий тип Item и есть конкретный тип для ячейки
На примере sealed class

```
sealed Item {
   object HeaderItem : Item()
   data class ContactItem(val contact: Contact) : Item()
   object FooterItem : Item()
}
```

2021-04-11 12:41 UTC, murrcha requested changes
С делегатами все гораздо проще
Добавила пример в репозиторий в ветку
https://github.com/Kimp13/clubhouse/tree/adapter-delegate-example

2021-04-11 12:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/decorations/ContactListDecoration.kt
> +            }, Paint().apply {
Здесь Paint создается каждый раз при вызове метода
Насколько вижу, сам объект не меняется, значит его можно вынести на уровень неизменяемой переменной класса

2021-04-11 14:12 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +            (differ.currentList[position] as? ContactListItem.Entity)
для чего использовать differ.currentList?
есть готовый метод getItems, который делает тоже самое

2021-04-11 14:14 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/ContactAdapter.kt
> +    fun setContactList(items: List<SimpleContactEntity>) {
этот метод не нужен

2021-04-11 14:14 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/adapters/decorations/ContactListDecoration.kt
> +        val paint = Paint().apply {
paint нужно вынести в переменную класса

2021-04-11 14:16 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/fragments/ContactListFragment.kt
> +                ContactListDecoration(
это тоже можно создать 1 раз при создании фрагмента и использовать потом много раз

2021-04-12 17:20 UTC, murrcha approved these changes
Остался последний комментарий
В остальном все хорошо
Плюс надо сдать ДЗ в classroom

2021-04-12 17:49 UTC, merged