Рефакторинг приложения с использованием RxJava
Kimp13/clubhouse pull request #9
Opened 2021-04-15 19:20 UTC by Kimp13

### Репозиторий
`ContactRepository` поменял свои взгляды и решил использовать RxJava (RxKotlin). `getSimpleContacts` использует `Flowable` и `Flowable.parallel` для достижения высокой скорости работы. Сам список контактов объявляется в функции и затем заполняется на первичном этапе для сохранения порядка контактов при использовании `parallel`. 

### `ViewModel`и
Теперь в каждой вьюмодели доступно поле `throwable: LiveData<Throwable>`, которое оповещает подписчиков об ошибке в репозитории. В `onCleared` и перед присваиванием `disposable` нового значения происходит `disposable.dispose()`.

### `RecyclerView` со списком контактов
Появилось 2 новых делегата: один для индикации загрузки, второй - для оповещения об ошибке.

2021-04-16 17:37 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/BirthdayNotificationService.kt
> +                disposable = ContactRepository.getContact(
где происходит отписка?

2021-04-16 17:38 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/RebootReminderService.kt
> +                    disposable = ContactRepository.getContacts(
аналогично, не вижу где отписываемся

2021-04-16 17:42 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/BirthdayNotificationService.kt
> +                disposable = ContactRepository.getContact(
нашла

2021-04-16 17:45 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Flowable.create<Int>({ emitter ->
Нужно создавать Single

2021-04-16 17:45 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Observable.merge<ContactEntity> {
Аналогично - нужен  Single

2021-04-16 17:46 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
шедулеры в репозитории не указывают обычно, это делается при подписке

2021-04-16 17:46 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
```
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
```
не нужны в репозитории, указывать нужно при подписке

2021-04-16 17:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Maybe.create<ContactEntity> { emitter ->
Аналогично, Single либо ошибка

2021-04-16 17:47 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
также убрать шедулеры из репозитория

2021-04-16 17:50 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactDetailsViewModel.kt
> +        ).subscribeBy(
При подписке нужно указать шедулеры, где подписаться, где ожидать

2021-04-16 17:50 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/viewmodels/ContactListViewModel.kt
> +        ).subscribeBy(
аналогично, указать где подписаться, где ожидать

2021-04-16 17:51 UTC, murrcha requested changes
Оставила комментарии

2021-04-17 07:43 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Maybe.create<ContactEntity> { emitter ->
Можно ли использовать в таком случае `!!`?

2021-04-17 07:43 UTC, Kimp13 commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Flowable.create<Int>({ emitter ->
Забыть о параллельности? Или отыскать секретный способ?

2021-04-18 08:35 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Maybe.create<ContactEntity> { emitter ->
!! - не используется на проектах

2021-04-18 08:43 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Flowable.create<Int>({ emitter ->
О какой параллельности идет речь? 
в данном случае нужно у провайдера запросить список контактов и все, это разовая операция

2021-04-18 09:37 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Flowable.create<Int>({ emitter ->
Плюс метод очень большой, нужно разбить на части для улучшения читаемости

2021-04-18 11:38 UTC, Kimp13 commented
Попробовал ещё укоротить метод `ContactRepository.getContact`, добавив контакту `Builder` для постепенного конструирования контакта при прохождении курсором, а репозиторию - `HashMap`, связывающий `CONTENT_ITEM_TYPE` строки с функцией для её обработки.

2021-04-18 16:28 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Single.create { emitter ->
Single.fromCallable не подходит?

2021-04-18 16:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactEntity.kt
> +    class Builder {
Слишком усложняешь, достаточно обычного data class

2021-04-18 16:34 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactRepository.kt
> +        return Single.create { emitter ->
Single.fromCallable?

2021-04-18 16:39 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/RebootReminderService.kt
> +                    disposable = ContactRepository.getContacts(
можно использовать функцию расширение addTo(disposable)

2021-04-18 16:40 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/ui/services/StartedContactService.kt
> +    protected var disposable: Disposable? = null
лучше тогда контейнер для подписок CompositeDisposable

2021-04-18 18:10 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactEntity.kt
> +        val emails: MutableList<String> = mutableListOf(),
MutableList - List

2021-04-18 18:11 UTC, murrcha commented on app/src/main/java/com/example/clubhouse/data/ContactEntity.kt
> +    data class Builder(
имела в виду что для data class билдер не нужен

2021-04-18 18:30 UTC, Kimp13 commented
Сделал всё как в старые добрые 12 часов назад

2021-04-19 08:47 UTC, murrcha approved these changes
Принято

2021-04-19 09:04 UTC, closed without merging